### ISSUE TITLE
Cutoff date for entry + gh-pages

### ISSUE THREAD

**Issue by le717** [github/game-off-2013#11]
1. By when do we have to fork the repo to enter? I only learned about this yesterday (and ran a concept in my head last night), and if I can find time from college work I want to join. I just don't know by when I must enter.
2. Can the game be hosted on GitHub Pages, and is at a requirement to push the the `master` branch? Can I push to `gh-pages` instead, or do I need to simply sync a `gh-pages` branch with the changes from `master`?

**Comment by leereilly** [comment]
Hi,

Great questions! You can fork the repo any time i.e. right now. There's no requirement to host the game on GitHub Pages. I may be biased, but I think you should :smiley: You're free to use whatever approach you like, but using `gh-pages` as the default branch sounds like a good idea.

Cheers,
  Lee :beers:
