### ISSUE TITLE
Private repository at start, public at the end

### ISSUE THREAD

**Issue by valryon** [github/game-off-2013#16]
Hello,

Is it allowed to fork the _github/game-off-2013_ repository into a private one, and make it public it just before the end of the contest?

It's just that I would like to test and idea before exposing it and if it's good enough, submit it to the contest.

Thanks.
Damien

**Comment by leereilly** [comment]
Hi there,

Great question. It's actually no longer possible to fork a public repository and make the fork private. There's no harm in participating and ending up with an incomplete or buggy game though.

Cheers and goo luck!
  Lee :beers:

**Comment by valryon** [comment]
Okay, I never tried to do so on GitHub but if the feature is disabled the question resolves by itself ;).

Thank you!
Damien
