### ISSUE TITLE
Submission timezone

### ISSUE THREAD

**Issue by jeroenverfallie** [github/game-off-2013#22]
Knowing I'll polish till the deadline, and so will many others, what's the exact end time for submissions, 1st of **December**, in what timezone?

Thanks

**Comment by lshulyay** [comment]
Very curious about this as well. Except I really hope it's first of _December_ as opposed to November, otherwise I've already missed the deadline!

**Comment by jeroenverfallie** [comment]
@leereilly Any thoughts on this yet?

**Comment by jeroenverfallie** [comment]
@drakonka Woops, thanks for pointing that out :sweat_smile:

**Comment by petarov** [comment]
A couple of hours more could be useful to finish up art and sounds, so this would be nice to know.

**Comment by leereilly** [comment]
Since December 1st is a Sunday, let's make the deadline midnight Sunday December 1st at midnight in your local timezone :)

Cheers,
  Lee :beers:

**Comment by jackhughesweb** [comment]
To clarify, is the deadline midnight Sat-Sun or Sun-Mon?

**Comment by jeroenverfallie** [comment]
@jackhughesweb Sun-Mon judging by this tweet: https://twitter.com/leereilly/status/406919414991179776 

@leereilly Cheers ;)

**Comment by petarov** [comment]
@leereilly  awesome ;)

**Comment by travisirby** [comment]
Great news, I was starting to panic :D Good luck finishing up everyone!
