### ISSUE TITLE
List of all 2013 entries

### ISSUE THREAD

**Issue by petarov** [github/game-off-2013#30]
I forked @pkukielka's [project](https://github.com/pkukielka/ggo12-viewer) from last year at http://petarov.github.io/ggo13-viewer/

This should contain a list of all 2013 entries/repos that have their Website URL set. Hopefully everyone's included!

Cheers :)

**Comment by travisirby** [comment]
Awesome job thanks! 
I just now added my URL, forgot last night :(
Does it update periodically?

**Comment by jeroenverfallie** [comment]
It's a static json. (I suppose due to the 6000 requests limit)
But I guess manual updates can be called _periodically_ too.

**Comment by petarov** [comment]
yeah, I'll have to update the `forks.json` file to refresh the entries. Will do that in a couple of hours. Pull requests are welcome as well ;)

**Comment by travisirby** [comment]
Interesting, thanks!

**Comment by kushalponam** [comment]
this is great!!. @petarov .
Thanks :)

**Comment by ZippoLag** [comment]
Awesome!

I've been wanting to check out other people's projects for a while now! :D

**Comment by pkukielka** [comment]
Great to see that this code is still useful :) I'm only sad that I totally missed game-off 2013 edition, somehow it slipped out unnoticed :(

**Comment by leereilly** [comment]
Sweet - thanks @petarov (and @pkukielka for the original work)!

Cheers,
  Lee :beers:

**Comment by petarov** [comment]
@pkukielka It works perfectly and I guess this could turn into something like an official Game-off tool, also for ggo14 ;) 
As for the ggo13 edition, I personally, found out about it from reddit. I rarely check on the github blog, so to be honest if it wasn't for reddit I would have missed it as well. :( 

@leereilly  Perhaps it's a good idea to have something like a Github events subscription or something in that direction.

**Comment by madmarcel** [comment]
Only 92 entries? Seems a bit low. 
Thanks for this by the way. It's working, I'm getting traffic referrals from the ggo13-viewer :)

**Comment by orendon** [comment]
wow I was expecting more than 92. Anyway cool, thanks.
